# jvm args
jvm.arg=-Dqingzhou.osgi.packages.extra=com.sun.management,sun.misc \
  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:7979 \
  -server -Xms128m -Xmx512m \
  -XX:+UseParallelGC \
  -Dqingzhou.features.disabled=qingzhou-agent,qingzhou-jdbc

# app
#app~qingzhou-admin-app.code=admin

# http
qingzhou-http-server.port=7900

# registry
qingzhou-registry.private_key=MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAK8bP/NIqvGaXslv6W6IBR/Ma8QIixqM4khN//EFj+pS8G4eeVZFNCdwiyTGrTZLqscZ0HLyTcxfYun3Wj3eDnxXN2QIY4Zjr2yUS+q8awmDGIfnaekZZBTsuGhnCkCZMhHSjQzA5qi3nK0y8VLtmdCO4Mz1GgbPs/duWikIcFZ/AgMBAAECgYAsvZCsb4/F5YR8gYyqQjTU+B083FX2dbLHeK6BfcNUwtZNvJmSEmKOBTJ4Ng9BxTmgX5ckF4cLRf/2+c1j613VuF6ki+4RSkB/SVjt8Br6uR5QiEodGmGFmRV68GNrSr0BVbDxUSJYdH2aVlKx0GSiM0n5YbgLV9D95kvynE48iQJBAO4QQF0TTRpSi7BjT2hs9w+ffUjOXkp/xq1Yknq98EgiXvjFHsKiv/oDhUG2tzj5T0wYJo0+4la3+yzUK4YWXnMCQQC8TLA0UPwdIzAleeajEGPQJiOjE781V+o5JqCGB7xqrgGaxjeeqIrAaQ/pFHJpNCYVY/92vXuGgltzaTRAjbjFAkAgmC8Hz1W2LekcTGyZ4pltFSwlJMQ6NQZxw3fCwHC+n54bN3n/siLQy1yaY7bwYQofZAsbOanpr6T/PUl8QWHLAkAoHkKwcsy0PIoGgglUlqpdb7LKDOwBJoD9ujAbPkyzge1Pl4nEIO6m/fto0nVp2rV+ezazir1ltCJd3X1Hf6ptAkEAp8D68AD1DoQ6LbCWVk/BOCZ95XcJyrAsqvUGQCaRYpJ1iJkm/Vv2nqpoMbrHqhN0pSJ4BrPXAjSo+n1iJi0nfw==
qingzhou-registry.interval=60
qingzhou-registry.timeout=120

# agent
qingzhou-agent.url=http://127.0.0.1:7900
qingzhou-agent.public_key=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCvGz/zSKrxml7Jb+luiAUfzGvECIsajOJITf/xBY/qUvBuHnlWRTQncIskxq02S6rHGdBy8k3MX2Lp91o93g58VzdkCGOGY69slEvqvGsJgxiH52npGWQU7LhoZwpAmTIR0o0MwOaot5ytMvFS7ZnQjuDM9RoGz7P3blopCHBWfwIDAQAB
qingzhou-agent.interval=60

# logger
qingzhou-logger.writingthread=true
qingzhou-logger.writer_console=console
qingzhou-logger.writer_console.level=info
qingzhou-logger.writer_console.format={date} [{level}] {message}
qingzhou-logger.writer_file=rolling file
qingzhou-logger.writer_file.file=logs/server_{date:yyyy-MM-dd}_{count}.log
qingzhou-logger.writer_file.level=info
qingzhou-logger.writer_file.format={date} [{level}] {message}
qingzhou-logger.writer_file.policies=size: 50MB,daily
qingzhou-logger.writer_file.backups=50
qingzhou-logger.writer_file.latest=logs/server.log
qingzhou-logger.writer_file.buffered=true
qingzhou-logger.writer_file.charset=UTF-8
qingzhou-logger.writer_file.convert=gzip

# jdbc
#qingzhou-jdbc~h2.url=jdbc:h2:mem:test
#qingzhou-jdbc~h2.username=sa
#qingzhou-jdbc~h2.password=
#qingzhou-jdbc~h2.dataSourceClassName=org.h2.jdbcx.JdbcDataSource
#qingzhou-jdbc~h2.maxActive=20
#qingzhou-jdbc~h2.testWhileIdle=true

# ai
#qingzhou-ai.base_url=https://open.bigmodel.cn/api/paas/v4
#qingzhou-ai.api_key=YOUR_API_KEY
#qingzhou-ai.model=GLM-4.7-Flash
