# Common
app~qingzhou-app-redis.1.active=true
app~qingzhou-app-redis.1.name=??
app~qingzhou-app-redis.1.mode=standalone
app~qingzhou-app-redis.1.envType=development
app~qingzhou-app-redis.1.password=

# standalone
app~qingzhou-app-redis.1.host=127.0.0.1
app~qingzhou-app-redis.1.port=6379
app~qingzhou-app-redis.1.database=0

# sentinel
app~qingzhou-app-redis.2.active=false
app~qingzhou-app-redis.2.mode=sentinel
app~qingzhou-app-redis.2.sentinelNodes=host1:port1\nhost2:port2
app~qingzhou-app-redis.2.sentinelMaster=mymaster

# cluster
app~qingzhou-app-redis.3.active=false
app~qingzhou-app-redis.3.mode=cluster
app~qingzhou-app-redis.3.clusterNodes=host1:port1\nhost2:port2